/**
 * Rewards view actions
 */
import createActionTypes from '../../../utils/action-type-factory';

const REWARDS_TYPES = createActionTypes('REWARDS_TYPES', [
  'GET_AVAILABLE_REWARDS',
  'GET_AVAILABLE_REWARDS_SUCCESS',
  'GET_AVAILABLE_REWARDS_FAILURE',

  'GET_AVAILABLE_REDEMPTIONS',
  'GET_AVAILABLE_REDEMPTIONS_SUCCESS',
  'GET_AVAILABLE_REDEMPTIONS_FAILURE',

  'ACCEPT_REFUND_AND_APPROVAL',
  'ACCEPT_REFUND_AND_APPROVAL_SUCCESS',
  'ACCEPT_REFUND_AND_APPROVAL_FAILURE',

  'CREATE_REWARD',
  'CREATE_REWARD_SUCCESS',
  'CREATE_REWARD_FAILURE',

  'EDIT_REWARD',
  'EDIT_REWARD_SUCCESS',
  'EDIT_REWARD_FAILURE',

  'SELECT_REWARD',

  'GET_REWARDS_BANK',
  'GET_REWARDS_BANK_SUCCESS',
  'GET_REWARDS_BANK_FAILURE',

  'UPDATE_REWARD_STATUS_REQUEST',
  'UPDATE_REWARD_STATUS_SUCCESS',
  'UPDATE_REWARD_STATUS_FAILURE',

  'DELETE_REWARD_REQUEST',
  'DELETE_REWARD_SUCCESS',
  'DELETE_REWARD_FAILURE',

  'ADD_REWARDS_BANK_ITEM_REQUEST',
  'ADD_REWARDS_BANK_ITEM_SUCCESS',
  'ADD_REWARDS_BANK_ITEM_FAILURE',
]);

export default REWARDS_TYPES;
