/**
 * Dashboard view actions
 */
import createActionTypes from '../../../utils/action-type-factory';

const DASHBOARD_TYPES = createActionTypes('DASHBOARD_TYPES', [
  'GET_ONLINE_STREAMERS_REQUEST',
  'GET_ONLINE_STREAMERS_SUCCESS',
  'GET_ONLINE_STREAMERS_FAILURE',

  'GET_YOUR_GROUPS_REQUEST',
  'GET_YOUR_GROUPS_SUCCESS',
  'GET_YOUR_GROUPS_FAILURE',

  'GET_ONLINE_FRIENDS_REQUEST',
  'GET_ONLINE_FRIENDS_SUCCESS',
  'GET_ONLINE_FRIENDS_FAILURE',

  'UPDATE_SOCIALS_STATUS',

  'GET_USER_PROFILE',
  'GET_USER_PROFILE_SUCCESS',
  'GET_USER_PROFILE_FAILURE',

  'GET_TWITCH_USER',
  'GET_TWITCH_USER_SUCCESS',
  'GET_TWITCH_USER_FAILURE',

  'SELECT_ONLINE_STREAMER'
]);

export default DASHBOARD_TYPES;
